apiVersion: v1
kind: Pod
metadata: 
  name: readinessprobe-pod
  labels:
    app: ready
spec:
  containers:
    - name: nginx-container
      image: nginx
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 5
