apiVersion: v1
kind: Pod
metadata:
  name: startupprobe-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      startupProbe:
        httpGet:
          path: /
          port: 80
        failureThreshold: 30
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
