apiVersion: v1
kind: Pod
metadata:
  name: tcpsocketprobe-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      livenessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
